offer:
  http:
    client:
      config:
        fetcherRunOccurrence: PT1s

scheduling:
  enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
#    org.springframework.security: DEBUG